const cats=[['All','🛒'],['Electronics','📱'],['Fashion','👕'],['Home','🏠'],['Beauty','🧴'],['Grocery','🥫'],['Sports','⚽'],['Books','📚']];
let products=[],cart=JSON.parse(localStorage.getItem('ba_cart')||'[]'),wishlist=JSON.parse(localStorage.getItem('ba_wishlist')||'[]'),orders=[],selected='All',query='',sort='popular',session=null,user=null;
const $=s=>document.querySelector(s), money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const defaultData={products:[{id:'demo-1',name:'Smartphone Pro X',category:'Electronics',price:24999,old_price:29999,rating:4.7,stock:24,badge:'Bestseller',description:'Fast everyday smartphone with a vivid display, capable camera and all-day battery.'},{id:'demo-2',name:'Wireless Headphones',category:'Electronics',price:1999,old_price:2999,rating:4.5,stock:42,badge:'Hot Deal',description:'Comfortable wireless headphones with rich sound and long battery life.'},{id:'demo-3',name:'Classic Running Shoes',category:'Fashion',price:1799,old_price:2499,rating:4.4,stock:35,badge:'Trending',description:'Lightweight everyday running shoes designed for comfort and movement.'}],orders:[]};
function configured(){const c=window.BUY_ANYTIME_CONFIG||{};return c.API_BASE_URL&&c.API_BASE_URL.startsWith('https://')&&c.SUPABASE_URL&&c.SUPABASE_URL.includes('supabase.co')&&!c.SUPABASE_PUBLISHABLE_KEY.includes('YOUR_')}
let sb=null;
if(window.BUY_ANYTIME_CONFIG?.SUPABASE_URL&&!window.BUY_ANYTIME_CONFIG.SUPABASE_URL.includes('YOUR_')){const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';sc.onload=()=>{sb=window.supabase.createClient(window.BUY_ANYTIME_CONFIG.SUPABASE_URL,window.BUY_ANYTIME_CONFIG.SUPABASE_PUBLISHABLE_KEY);sb.auth.getSession().then(({data})=>{session=data.session;user=data.session?.user||null;});sb.auth.onAuthStateChange((_e,s)=>{session=s;user=s?.user||null;});loadStore()};document.head.appendChild(sc)}
async function api(path,opt={}){const c=window.BUY_ANYTIME_CONFIG||{};const h={'Content-Type':'application/json',...(opt.headers||{})};if(session?.access_token)h.Authorization='Bearer '+session.access_token;const r=await fetch(c.API_BASE_URL+path,{...opt,headers:h});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function loadStore(){try{const j=await api('/api/products');products=j.products||[]}catch(e){products=defaultData.products}orders=session?((await api('/api/orders').catch(()=>({orders:[]}))).orders||[]):[];renderNav();go('home');updateCart()}
function renderNav(){ $('#nav').innerHTML=cats.map(c=>`<button onclick="filterCat('${c[0]}')">${c[1]} ${c[0]}</button>`).join('')+'<button onclick="go(\'admin\')">⚙ Admin</button>'; }
function filterCat(c){selected=c;go('shop')} function doSearch(){query=$('#search').value.trim();go('shop')}
function save(){localStorage.setItem('ba_cart',JSON.stringify(cart));localStorage.setItem('ba_wishlist',JSON.stringify(wishlist));updateCart()} function updateCart(){const n=cart.reduce((s,i)=>s+i.qty,0);if($('#cartCount'))$('#cartCount').textContent=n;if($('#mobileCartCount'))$('#mobileCartCount').textContent=n}
function productCard(p){const wish=wishlist.includes(p.id);const pic=p.image_url?`<img src="${p.image_url}" alt="${p.name}">`:p.category==='Electronics'?'📱':p.category==='Fashion'?'👕':'📦';return `<article class="card"><span class="badge">${p.badge||'New'}</span><div class="pic" onclick="go('product','${p.id}')">${pic}</div><div class="card-body"><h3>${p.name}</h3><span class="price">${money(p.price)}</span> <span class="old">${money(p.old_price)}</span><div class="rating">★ ${p.rating||0} • ${p.category} • ${p.stock} left</div><div class="card-actions"><button class="add" onclick="event.stopPropagation();toggleWish('${p.id}')">${wish?'♥ Saved':'♡ Wishlist'}</button><button class="buy" onclick="event.stopPropagation();addCart('${p.id}')">Add to cart</button></div></div></article>`}
function home(){return `<main><section class="hero"><div><div class="eyebrow">BUY ANYTIME • LIVE STORE</div><h1>Everything you need.<br><span>Anytime you want.</span></h1><p>Real products, live stock and secure checkout.</p><button class="btn primary" onclick="go('shop')">Shop now →</button></div><div class="hero-art"><div class="emoji">🛍️</div><strong>Live inventory. Secure payments.</strong><p>${configured()?'Connected to your cloud store.':'Setup required for live mode.'}</p></div></section><section class="section"><div class="section-head"><h2>Shop by category</h2></div><div class="categories">${cats.slice(1).map(c=>`<div class="cat" onclick="filterCat('${c[0]}')"><div class="ico">${c[1]}</div><strong>${c[0]}</strong></div>`).join('')}</div></section><section class="section"><div class="section-head"><h2>Popular products</h2></div><div class="grid">${products.slice(0,8).map(productCard).join('')}</div></section></main>`}
function shop(){let arr=products.filter(p=>(selected==='All'||p.category===selected)&&(`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase())));if(sort==='low')arr.sort((a,b)=>a.price-b.price);if(sort==='high')arr.sort((a,b)=>b.price-a.price);if(sort==='rating')arr.sort((a,b)=>(b.rating||0)-(a.rating||0));return `<main class="page"><div class="section-head"><div><h2>Shop ${selected==='All'?'All Products':selected}</h2><p style="color:var(--muted)">${arr.length} products found</p></div><div class="toolbar"><button class="btn light" onclick="selected='All';query='';$('#search').value='';go('shop')">Reset</button><select onchange="sort=this.value;go('shop')"><option value="popular">Popular</option><option value="low">Price low-high</option><option value="high">Price high-low</option><option value="rating">Top rated</option></select></div></div>${arr.length?`<div class="grid">${arr.map(productCard).join('')}</div>`:`<div class="panel empty">No products found.</div>`}</main>`}
function productPage(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return `<main class="page"><div class="panel">Product not found.</div></main>`;return `<main class="page"><button class="btn light" onclick="go('shop')">← Back</button><div class="panel detail" style="margin-top:15px"><div class="detail-pic">${p.image_url?`<img src="${p.image_url}" alt="${p.name}">`:'📦'}</div><div><div class="rating">★ ${p.rating||0} rating</div><h1>${p.name}</h1><p>${p.description||''}</p><div><span class="price">${money(p.price)}</span> <span class="old">${money(p.old_price)}</span></div><p>✓ Secure checkout &nbsp; ✓ Order tracking</p><div class="qty"><button onclick="changeTemp(-1)">−</button><strong id="tempQty">1</strong><button onclick="changeTemp(1)">+</button></div><button class="btn primary" onclick="addCart('${p.id}',tempQty)">Add to cart</button> <button class="btn light" onclick="toggleWish('${p.id}')">${wishlist.includes(p.id)?'♥ Saved':'♡ Wishlist'}</button></div></div></main>`}
let tempQty=1;function changeTemp(n){tempQty=Math.max(1,tempQty+n);if($('#tempQty'))$('#tempQty').textContent=tempQty}
function addCart(id,qty=1){const p=products.find(x=>String(x.id)===String(id));if(!p)return;qty=Math.max(1,Number(qty)||1);const row=cart.find(x=>String(x.id)===String(id));const next=(row?row.qty:0)+qty;if(next>p.stock){toast('Not enough stock',true);return}if(row)row.qty=next;else cart.push({id:p.id,qty});save();toast(`${p.name} added to cart`)}
function toggleWish(id){id=String(id);wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();go(location.hash.includes('shop')?'shop':'home')}
function cartPage(){const items=cart.map(i=>{const p=products.find(x=>String(x.id)===String(i.id));return p?`<div class="cart-row"><div class="cart-thumb">📦</div><div><h4>${p.name}</h4><small>${money(p.price)} each</small></div><div class="qty"><button onclick="cartQty('${p.id}',-1)">−</button><strong>${i.qty}</strong><button onclick="cartQty('${p.id}',1)">+</button></div><strong>${money(p.price*i.qty)}</strong></div>`:''}).join('');const total=cart.reduce((s,i)=>{const p=products.find(x=>String(x.id)===String(i.id));return s+(p?p.price*i.qty:0)},0);return `<main class="page"><div class="section-head"><h2>Your Cart</h2></div>${items||'<div class="panel empty">Your cart is empty.</div>'}<div class="panel" style="margin-top:15px"><h3>Total: ${money(total)}</h3><button class="btn primary" ${cart.length?'':'disabled'} onclick="go('checkout')">Checkout</button></div></main>`}
function cartQty(id,n){const r=cart.find(x=>String(x.id)===String(id));if(!r)return;r.qty+=n;if(r.qty<=0)cart=cart.filter(x=>String(x.id)!==String(id));save();go('cart')}
function checkout(){if(!cart.length)return `<main class="page"><div class="panel empty">Cart is empty.</div></main>`;if(!user)return `<main class="page"><div class="panel empty"><h2>Please login</h2><p>Login with your mobile number before checkout.</p><button class="btn primary" onclick="openLogin()">Login</button></div></main>`;return `<main class="page"><div class="section-head"><h2>Secure Checkout</h2></div><div class="panel"><h3>Delivery address</h3><textarea id="address" rows="5" placeholder="Name, phone, address, city, state, pincode" required></textarea><p>Payment: Razorpay (UPI / cards / supported methods)</p><button class="btn primary" onclick="placeOrder()">Pay ${money(cart.reduce((s,i)=>{const p=products.find(x=>String(x.id)===String(i.id));return s+(p?p.price*i.qty:0)},0))}</button></div></main>`}
async function placeOrder(){try{const address={raw:$('#address').value};if(!address.raw)return toast('Enter delivery address',true);const items=cart.map(i=>({productId:i.id,quantity:i.qty}));const x=await api('/api/orders/create',{method:'POST',body:JSON.stringify({items,address})});if(!x.razorpayConfigured||!window.Razorpay){toast('Payment gateway is not configured yet',true);return}const options={key:window.BUY_ANYTIME_CONFIG.RAZORPAY_KEY_ID||x.razorpayKeyId,amount:x.amount,currency:x.currency,name:'Buy Anytime',description:'Buy Anytime order '+x.order.id,order_id:x.razorpayOrderId,prefill:{contact:user?.phone||''},theme:{color:'#1E40AF'},handler:async function(resp){try{await api('/api/payments/verify',{method:'POST',body:JSON.stringify({orderId:x.order.id,razorpay_order_id:resp.razorpay_order_id,razorpay_payment_id:resp.razorpay_payment_id,razorpay_signature:resp.razorpay_signature})});cart=[];save();localStorage.setItem('ba_last_order',x.order.id);toast('Payment successful');go('orders')}catch(e){toast(e.message,true)}}};const rzp=new Razorpay(options);rzp.on('payment.failed',function(){toast('Payment failed. Your order remains pending.',true)});rzp.open()}catch(e){toast(e.message,true)}}
async function ordersPage(){try{orders=(await api('/api/orders')).orders||[]}catch(e){orders=[]}return `<main class="page"><div class="section-head"><h2>My Orders</h2></div>${orders.length?orders.map(o=>`<div class="panel" style="margin-bottom:12px"><strong>${o.id}</strong><p>${money(o.total)} • Payment: ${o.payment_status}</p><span class="status">${o.status}</span></div>`).join(''):'<div class="panel empty">No orders yet.</div>'}</main>`}
function admin(){return `<main class="page"><div class="panel"><h2>Admin</h2><p>Admin management is now server-protected.</p><p>Open the deployed Admin Dashboard URL and sign in with your configured admin account.</p></div></main>`}
function openLogin(){modal(`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>Login to Buy Anytime</h2><p style="color:var(--muted)">Real SMS OTP login.</p><form class="form" onsubmit="sendOtp(event)"><div class="login-phone-row"><div class="country-code">🇮🇳 +91</div><input name="phone" inputmode="tel" maxlength="10" required placeholder="10-digit mobile number" oninput="this.value=this.value.replace(/\D/g,'').slice(0,10)"></div><button class="btn primary">Send OTP</button></form></div>`)}
async function sendOtp(e){e.preventDefault();const phone='+91'+e.target.phone.value;if(!sb){toast('Configure Supabase first',true);return}const {error}=await sb.auth.signInWithOtp({phone});if(error){toast(error.message,true);return}modal(`<div class="modal-card"><button class="close" onclick="closeModal()">×</button><h2>Verify mobile number</h2><p>OTP sent to ${phone}.</p><form class="form" onsubmit="verifyOtp(event,'${phone}')"><input name="otp" inputmode="numeric" maxlength="6" required placeholder="6-digit OTP"><button class="btn primary">Verify & Continue</button></form></div>`)}
async function verifyOtp(e,phone){e.preventDefault();const {data,error}=await sb.auth.verifyOtp({phone,token:e.target.otp.value.trim(),type:'sms'});if(error){toast(error.message,true);return}session=data.session;user=data.user;closeModal();toast('Mobile number verified');renderRoute(location.hash.slice(1).split('/')[0]||'home')}
function init(){renderNav();go('home');updateCart();const b=$('#cartButton');if(b){b.addEventListener('click',openCart)} if(!sb)loadStore()}
function go(page,id){tempQty=1;location.hash=page+(id?'/'+id:'');renderRoute(page,id)} async function renderRoute(page,id){if(!page)page='home';let html=page==='home'?home():page==='shop'?shop():page==='product'?productPage(id):page==='checkout'?checkout():page==='orders'?await ordersPage():page==='cart'?cartPage():page==='admin'?admin():home();$('#app').innerHTML=html;window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>{const [p,id]=location.hash.slice(1).split('/');renderRoute(p,id)});function openCart(){go('cart')}function modal(html){$('#modal').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}function toast(msg,bad=false){const d=document.createElement('div');d.textContent=msg;d.style='position:fixed;bottom:22px;left:50%;transform:translateX(-50%);z-index:120;background:'+(bad?'#d92d20':'#111827')+';color:white;padding:12px 18px;border-radius:10px;font-weight:700';document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
init();
